import { defineConfig } from 'oxlint';
import core from 'ultracite/oxlint/core';
import react from 'ultracite/oxlint/react';
import tanstack from 'ultracite/oxlint/tanstack';

export default defineConfig({
  extends: [core, react, tanstack],
  ignorePatterns: [...core.ignorePatterns, '**/routeTree.gen.ts'],
  rules: {
    'class-methods-use-this': 'off',
    'eslint/no-template-curly-in-string': 'off',
    'eslint/prefer-template': 'off',
    'eslint/curly': 'off',
    'eslint/arrow-body-style': 'off',
    'react/jsx-pascal-case': 'off',
    'unicorn/prefer-at': 'off',
    'eslint/max-classes-per-file': 'off',
    'eslint/no-await-in-loop': 'off',
    'eslint/no-bitwise': 'off',
    'eslint/no-empty-function': 'off',
    'eslint/no-inline-comments': 'off',
    'eslint/no-nested-ternary': 'off',
    'eslint/no-negated-condition': 'off',
    'eslint/no-unused-vars': 'off',
    'eslint/no-use-before-define': 'off',
    'eslint/no-warning-comments': 'off',
    'eslint/prefer-named-capture-group': 'off',
    'eslint/prefer-promise-reject-errors': 'off',
    'eslint/require-unicode-regexp': 'off',
    'func-style': 'off',
    'import/consistent-type-specifier-style': 'off',
    'import/first': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/label-has-associated-control': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'off',
    'jsx-a11y/prefer-tag-over-role': 'off',
    'jsdoc/check-tag-names': 'off',
    'jsdoc/require-param-description': 'off',
    'oxc/no-barrel-file': 'off',
    'promise/avoid-new': 'off',
    'promise/prefer-await-to-callbacks': 'off',
    'promise/prefer-await-to-then': 'off',
    'react/display-name': 'off',
    'react/exhaustive-effect-dependencies': 'off',
    'react/function-component-definition': 'off',
    'react/hook-use-state': 'off',
    'react/no-danger': 'off',
    'react/set-state-in-effect': 'off',
    'react/todo': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
    'require-await': 'off',
    'sort-keys': 'off',
    'typescript/consistent-type-imports': 'off',
    'typescript/method-signature-style': 'off',
    'typescript/no-dynamic-delete': 'off',
    'typescript/no-empty-interface': 'off',
    'typescript/no-empty-object-type': 'off',
    'typescript/no-explicit-any': 'off',
    'typescript/no-invalid-void-type': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/parameter-properties': 'off',
    'typescript/prefer-for-of': 'off',
    'typescript/triple-slash-reference': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-lonely-if': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/no-this-assignment': 'off',
    'unicorn/prefer-add-event-listener': 'off',
    'unicorn/prefer-code-point': 'off',
    'eslint/prefer-destructuring': 'off',
    'unicorn/prefer-export-from': 'off',
    'unicorn/prefer-number-coercion': 'off',
    'unicorn/prefer-single-call': 'off',
    'unicorn/prefer-ternary': 'off',
  },
});
